({
    mustDeps: [
        'credit-all',
        'credit-finish',
        'credit-new',
        'credit-active',
        'credit-archive',
        'credit-pay',
        'deposit-all',
        'deposit-new',
        'deposit-active',
        'deposit-archive',
        'application',
        'board',
        'info',
        'validator',
        'settings',
        'reset',
        'help'
    ]
})
